### ISSUE TITLE
Module not found: Package path ./tldraw.css

### ISSUE THREAD

**Issue by tpn-ikuto-ishihara** [tldraw/make-real-starter#13]
This error occurred and the module was not included.
"Module not found: Package path ./tldraw.css"

**Comment by ThariqS** [comment]
I get this as well!

**Comment by justintout** [comment]
Try pinning to the exact `@tldraw/tldraw` version specified in `package.json`, instead of accepting the compatible (`^`) versions. Re-install afterward. 

`"@tldraw/tldraw": "2.0.0-canary.ba4091c59418",`

**Comment by tpn-ikuto-ishihara** [comment]
After Re-install, it worked. thanks.
