### ISSUE TITLE
getSelectedShapes is not a function + other strange behavior

### ISSUE THREAD

**Issue by elliotBraem** [tldraw/make-real-starter#4]
This happened with the original [tldraw/draw-a-ui](https://github.com/tldraw/draw-a-ui) repository too, but the error was ```tldraw/tldraw.css``` not found.

If you are experiencing strange behavior like this, I've had to update the dependency from:

```"@tldraw/tldraw": "^2.0.0-canary.ba4091c59418",```
to
```"@tldraw/tldraw": "2.0.0-canary.ba4091c59418",```

(remove ^)

I'm not sure why this fixes it or what the issue is. There may be some inconsistency with how the package is being released. 

Running on Mac OS Ventura, using node v21.1.0 (npm v10.2.0).

**Comment by TodePond** [comment]
Hey I just tried out the template in a fresh repo and I didn't get this issue. Hopefully this issue has resolved itself now

**Comment by elliotBraem** [comment]
Just tried with fresh repo and looks resolved! Thanks.
